/*
 * Reporte de Crédito Consolidado Personas Morales
 * <p>PI Reporte de Crédito Consolidado de Personas Morales. <br/><br><img src='https://developer.circulodecredito.com.mx/sites/default/files/2024-01/Logo-Swaggers.png' height='70' width='270'/></p><br/>
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@circulodecredito.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 package com.cdc.apihub.mx.RCCPMV2.test;

import java.util.concurrent.TimeUnit;

import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.cdc.apihub.mx.RCCPMV2.client.ApiClient;
import com.cdc.apihub.mx.RCCPMV2.client.ApiException;
import com.cdc.apihub.mx.RCCPMV2.client.ApiResponse;
import com.cdc.apihub.mx.RCCPMV2.client.api.RCCPMV2Api;
import com.cdc.apihub.mx.RCCPMV2.client.interceptor.SignerInterceptor;
import com.cdc.apihub.mx.RCCPMV2.client.model.CatalogoEstados;
import com.cdc.apihub.mx.RCCPMV2.client.model.CatalogoPais;
import com.cdc.apihub.mx.RCCPMV2.client.model.Persona;
import com.cdc.apihub.mx.RCCPMV2.client.model.PersonaDomicilio;
import com.cdc.apihub.mx.RCCPMV2.client.model.PersonaPeticion;
import com.cdc.apihub.mx.RCCPMV2.client.model.ReporteRespuesta;
import okhttp3.OkHttpClient;

public class ApiTest {
    
    private Logger logger = LoggerFactory.getLogger(ApiTest.class.getName());
    
    private final RCCPMV2Api api = new RCCPMV2Api();

    private ApiClient apiClient = null;

    private String keystoreFile = "your_path_for_your_keystore/keystore.jks";
    private String cdcCertFile = "your_path_for_certificate_of_cdc/cdc_cert.pem";
    private String keystorePassword = "your_super_secure_keystore_password";
    private String keyAlias = "your_key_alias";
    private String keyPassword = "your_super_secure_password";
    
    private String usernameCDC = "your_username_otrorgante";
    private String passwordCDC = "your_password_otorgante"; 
    
    private String url = "the_url";
    private String xApiKey = "X_Api_Key";
    
    private SignerInterceptor interceptor;
    
    @Before()
    public void setUp() {
        interceptor = new SignerInterceptor(keystoreFile, cdcCertFile, keystorePassword, keyAlias, keyPassword);
        this.apiClient = api.getApiClient();
        this.apiClient.setBasePath(url);
        OkHttpClient okHttpClient = new OkHttpClient().newBuilder()
                .readTimeout(30, TimeUnit.SECONDS)
                .addInterceptor(interceptor)
                .build();
        apiClient.setHttpClient(okHttpClient);
    }

    @Test
    public void getReporteCreditoPMV2Test() throws ApiException {

        PersonaPeticion request = new PersonaPeticion();
        Persona persona = new Persona();
        PersonaDomicilio domicilio = new PersonaDomicilio();
        
        Integer estatusOK = 200;
        Integer estatusNoContent = 204;
        
        try {
            
            domicilio.setDireccion("CALLE DEL CENTENO 14 0");
            domicilio.setColoniaPoblacion("LAS PALMAS");
            domicilio.setDelegacionMunicipio("CUAJIMALPA DE MORELOS");
            domicilio.setCiudad("CUAJIMALPA DE MORELOS");
            domicilio.setEstado(CatalogoEstados.DF);
            domicilio.setCP("05210");
            domicilio.setPais(CatalogoPais.MX);

            persona.setRFC("ETS980201AN1");
            persona.setNombre("EMPRESA TESTER SA DE CV");
            persona.setDomicilio(domicilio);

            request.setFolioOtorgante("1000001");
            request.setPersona(persona);
            
            ApiResponse<?> response = api.getReporteGenericCreditoPMV2(xApiKey, usernameCDC, passwordCDC, request);
  
            Assert.assertTrue(estatusOK.equals(response.getStatusCode()));
            
            if(estatusOK.equals(response.getStatusCode())) {
                ReporteRespuesta responseOK = (ReporteRespuesta) response.getData();
                logger.info("RCC-PM-V2 Test: " + responseOK.toString());
            }
            
        }catch (ApiException e) {
            if(!estatusNoContent.equals(e.getCode())) {
                logger.info("Error getReporteCreditoPMTest: " + e.getResponseBody());
            }
            Assert.assertTrue(estatusOK.equals(e.getCode()));
        }        
    }
    
}